name: webrtc_interface
description: WebRTC Interface for Dart.
version: 1.0.0
homepage: https://flutter-webrtc.org

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  sdp_transform: ^0.3.2

dev_dependencies:
  dart_code_metrics: ^4.4.0
  pedantic: ^1.11.0
  test: ^1.15.7
